### PR TITLE
Update README.rst with GPLv3 license info

### LINKED ISSUE #3: License terms
I think the README needs some discussion of the pyqt license terms, since if the user doesn't have a commercial license (and is using pyqt under GPL v3 instead) they will need to update the license for their own project to match.

> PyQt5 is released under the GPL v3 license and under a commercial license that allows for the development of proprietary applications.
https://pypi.org/project/PyQt5/

https://www.riverbankcomputing.com/commercial/license-faq

### PR DESCRIPTION
**Pull request by GenevieveBuckley**
Closes https://github.com/mandeep/cookiecutter-pyqt5/issues/3

### CODE REVIEW

**Comment by mandeep** [comment]
Thanks for the PR! Since the cookiecutter generates a LICENSE file that includes GPLv3 verbage, I think we need to either delete that file, or empty its contents.

**Comment by GenevieveBuckley** [comment]
> Thanks for the PR! Since the cookiecutter generates a LICENSE file that includes GPLv3 verbage, I think we need to either delete that file, or empty its contents.

I though the cookiecutter included an MIT license?

**Comment by mandeep** [comment]
The project cookiecutter-pyqt5 itself is MIT, however the newly created project spawned from the cookiecutter is GPLv3: https://github.com/mandeep/cookiecutter-pyqt5/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/LICENSE

**Comment by mandeep** [comment]
@GenevieveBuckley do you have any thoughts on this? Do you think we should be more explicit about the licenses involved?

**Comment by GenevieveBuckley** [comment]
Upon reflection, I think that's sufficient. I'll close the PR, thanks for following up on it!

**Comment by mandeep** [comment]
Thanks for your help with this!

**Pull request closed without merging**
